# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DinoPrez' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Google-Mobile-Ads-SDK'

  # Pods for DinoPrez

  target 'DinoPrezTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DinoPrezUITests' do
    # Pods for testing
  end

end
